name: CI

on:
  pull_request:
    branches: "main"
    paths:
      - "**.rs"
      - "**.toml"
      - "Cargo.lock"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:    
  validate-pull:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v3
    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.toolchain }}-
          ${{ runner.os }}-cargo-
          ${{ runner.os }}-
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy --toolchain ${{ matrix.toolchain }}
      # The library is designed on the stable branch, meaning the check should run on a stable version.
    - name: Validate Formatting
      if: matrix.toolchain == 'stable'
      run: cargo fmt --check --verbose
    - name: Validate Clippy
      run: cargo clippy -- -D warnings --verbose
    - name: Validate Standard Tests
      run: cargo test --verbose
